/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Modified to support custom material overrides and debug material applications
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Lantern-smallTextures.glb')
  const { overrideMaterials = {} } = props
  
  // Create refs for custom materials
  const customGlassMaterial = useRef(new THREE.MeshPhysicalMaterial({
    color: new THREE.Color(0xeeeeee),
    transparent: true,
    opacity: 0.7,
    refractionRatio: 0.8,
    transmission: 0.5,
    clearcoat: 0.5,
    clearcoatRoughness: 0.2,
    roughness: 0.1,
    metalness: 0.2,
    emissive: new THREE.Color(0xffcc77),
    emissiveIntensity: 0.3,
    side: THREE.DoubleSide
  }))
  
  // Log the nodes and materials to help debug
  useEffect(() => {
    console.log("Lantern nodes:", nodes)
    console.log("Lantern materials:", materials)
    console.log("Glass material settings:", customGlassMaterial.current)
  }, [nodes, materials])
  
  return (
    <group {...props} dispose={null}>
      {/* Apply our custom glass material directly to the glass meshes */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lantern-glass'].geometry}
        material={customGlassMaterial.current}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lantern-handle'].geometry}
        material={materials.handleWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lantern-rubber'].geometry}
        material={materials.rubber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lantern-inner-metal'].geometry}
        material={materials.normalMetal}
      />
      {/* This also appears to be glass, so apply our custom material */}
      <mesh 
        castShadow 
        receiveShadow 
        geometry={nodes.Circle.geometry} 
        material={customGlassMaterial.current} 
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_1.geometry}
        material={materials.metal}
      />
      
      {/* Add debug visualization for the glass mesh bounds */}
      <mesh>
        <boxGeometry args={[0.5, 0.5, 0.5]} />
        <meshBasicMaterial color="red" wireframe={true} visible={false} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/Lantern-smallTextures.glb')