/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Lantern-smallTextures.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lantern-glass'].geometry}
        material={materials.glass}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lantern-handle'].geometry}
        material={materials.handleWood}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lantern-rubber'].geometry}
        material={materials.rubber}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Lantern-inner-metal'].geometry}
        material={materials.normalMetal}
      />
      <mesh castShadow receiveShadow geometry={nodes.Circle.geometry} material={materials.glass} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle_1.geometry}
        material={materials.metal}
      />
    </group>
  )
}

useGLTF.preload('/Lantern-smallTextures.glb')