/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: sam (https://sketchfab.com/pigeons)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/low-poly-torches-06fa08b3b2834d26b3deee112eda2919
Title: low poly torches
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

const Torch = (props) => {
  const { nodes, materials } = useGLTF('/low_poly_torches.glb')
  
  // Create enhanced materials with emissive properties for the fire
  const enhancedMaterials = useMemo(() => {
    // Clone the fire material to add emissive properties
    const fireMaterial = materials.fire.clone();
    fireMaterial.emissive = new THREE.Color(0xff7700); // Orange-yellow emissive color
    fireMaterial.emissiveIntensity = 2.0; // Bright intensity
    
    // Clone the second fire material
    const fire2Material = materials.fire2wwwwww.clone();
    fire2Material.emissive = new THREE.Color(0xff3300); // Redder emissive for the inner flame
    fire2Material.emissiveIntensity = 1.8; // Slightly less intense
    
    return { 
      fire: fireMaterial, 
      fire2wwwwww: fire2Material 
    };
  }, [materials]);
  
  // Create a pointLight to illuminate the surrounding area
  const lightRef = useRef();
  
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.571, -0.01, -3.137]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[3248.475, 194.208, 0]} rotation={[0, 0, Math.PI]}>
            <group position={[268.874, 0, 1547.504]}>
              <group position={[1195.181, -28.878, -311.453]}>
                {/* Fire meshes with enhanced materials */}
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pCube361_fire_0.geometry}
                  material={enhancedMaterials.fire}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pCube361_fire2wwwwww_0.geometry}
                  material={enhancedMaterials.fire2wwwwww}
                />
                
                {/* Add a point light inside the fire */}
                <pointLight
                  ref={lightRef}
                  color="#ff6600"
                  intensity={1.5}
                  distance={5}
                  decay={2}
                  castShadow
                  shadow-bias={-0.0005}
                />
              </group>
              <group position={[1446.304, 0, -301.482]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pCylinder51_dark_metal_0.geometry}
                  material={materials.dark_metal}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pCylinder51_wood_2_0.geometry}
                  material={materials.wood_2}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pCylinder51_lambert1_0.geometry}
                  material={materials.lambert1}
                />
              </group>
              {/* <group position={[1298.303, 0, -301.482]}>
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pCylinder50_dark_metal_0.geometry}
                  material={materials.dark_metal}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pCylinder50_wood_2_0.geometry}
                  material={materials.wood_2}
                />
                <mesh
                  castShadow
                  receiveShadow
                  geometry={nodes.pCylinder50_lambert1_0.geometry}
                  material={materials.lambert1}
                />
              </group> */}
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/low_poly_torches.glb')

export default Torch