/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/woodenSword-smallerTextures.glb')
  return (
    <group {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.SWORD.geometry} material={materials.wood} />
    </group>
  )
}

useGLTF.preload('/woodenSword-smallerTextures.glb')

